### PR TITLE
Support file output, multithreading and add start and end EntryId for CTLogOutput in getLogEntries().

### PR DESCRIPTION
**Pull request by knikolov82**

### CODE REVIEW

**Comment by eranmes** [comment]
That's a very large change - please break it down to a series of commits, each introducing a single conceptual change. Reviewing it like this would take significantly longer.

Also, you're introducing a lot of new code without:
- Documenting the reasoning behind this new functionality.
- Adding tests.

Will be happy to chat out-of-band about how to re-structure this pull request.

**Comment by eranmes** [comment]
@knikolov82 ping - as a start, could you please break this down to several commits, each adding one piece of functionality?

**Comment by knikolov82** [comment]
@eranmes, yes I will try break this down into smaller pieces probably later this month. 
In the meantime, I think that it will be more reasonable to close this pull request and to create separate ones, once I am ready with the changes. Could you please share your thoughts on this?

**Comment by pphaneuf** [comment]
Yes, it makes sense to close this pull request, if you are going to file others that cover the same functionality.

I'll leave it to you. :smile:

**Comment by knikolov82** [comment]
Closing this pull request as changes will be separated into several smaller commits/pull requests

**Pull request closed without merging**
