### PR TITLE
Proposed protobuf changes to make the distinguished name fields of X509Description a bit more strongly typed.

### PR DESCRIPTION
**Pull request by phad**
I'd like to deprecate the existing ct.X509Description.{subject|issuer|subject_alternative_names|root_issuer} fields and introduce replacements that are more strongly typed.

The rationale for this is that the components of a Distinguished Name that most apps care about are predictable.  The current repeated DNAttribute fields are basically a string dictionary.  This doesn't lend itself to DB indexing, eg. if one wanted to build an index of subject CN fields.

### CODE REVIEW

**Comment by pphaneuf** [comment]
LGTM

**Comment by eranmes** [comment]
LGTM, it seems that the proto fields can be entirely removed rather than deprecated.

**Comment by phad** [comment]
OK, if you guys are happy for me to remove the existing protos straight away I'll make a bunch of commits and squash the eventual PR.

**Comment by pphaneuf** [comment]
You can delete them, but normally you'd leave a comment to say the the field identifier isn't available (to protect against stored protobufs being "re-interpreted" in the future). The ```deprecated``` tag kind of fill in this role, as well avoiding breaking existing code (which might still be referring to those fields.

If you know there's nothing using those fields, you could just remove them, yes (and maybe leave a comment to indicate which field IDs are no longer available).

**Comment by pphaneuf** [comment]
Abandoning this? Or closed by mistake?

**Pull request closed without merging**
