### PR TITLE
 Use CHECK instead of CHECK_NOTNULL.

### PR DESCRIPTION
**Pull request by ahedberg**
This provides better compatibility with more logging frameworks.

### CODE REVIEW

**Comment by daviddrysdale** [comment]
It's a bit hard to see what the real error is among all the deprecation warnings, but maybe:

```
________ running 'gnumake -f /Users/travis/build/google/ct/certificate-transparency/build.gclient _libevhtp' in '/Users/travis/build/google/ct'

gnumake -C libevhtp -f `pwd`/certificate-transparency/build/Makefile.libevhtp

gnumake

gnumake[2]: /usr/local/Cellar/cmake/3.9.4/bin/cmake: No such file or directory

gnumake[2]: *** [cmake_check_build_system] Error 1

gnumake[1]: *** [all] Error 2

gnumake: *** [_libevhtp] Error 2

Error: Command 'gnumake -f /Users/travis/build/google/ct/certificate-transparency/build.gclient _libevhtp' returned non-zero exit status 2 in /Users/travis/build/google/ct

travis_time:end:2ee0eb74:start=1534834590581453000,finish=1534834721219849000,duration=130638396000

The command "gclient sync --disable-syntax-validation" failed and exited with 2 during
```

There haven't been any changes to this repo for weeks, so it may be that the Travis OSX build environment has changed in the meanwhile?

**Comment by Martin2112** [comment]
Yep, looks like it could be unrelated to this PR.

**Comment by Martin2112** [comment]
Clearing the travis caches now shows two problems. The OSX build gets further but ends up failing on an unused `this` in etcd.o

The linux sanitized build now reproducibly crashes with:

```
Testing ciphersuites for TLSv1.2
Testing AES256-GCM-SHA384
Available compression methods:
  NONE
TLSv1.2, cipher TLSv1/SSLv3 AES256-GCM-SHA384, 2048 bit RSA
1 handshakes of 256 bytes done
Testing AES256-SHA256
Available compression methods:
  NONE
Illegal instruction (core dumped)
Failed AES256-SHA256
```

**Comment by AlCutter** [comment]
Any reason not just just remove the `this` from the lambda capture?

**Comment by AlCutter** [comment]
Is this relevant to the SIGILL issue:
  https://stackoverflow.com/questions/48517002/illegal-instruction-error-with-openssl
?

**Comment by AlCutter** [comment]
Sorry, I skimmed your earlier comment rather than reading properly, and the OS X bit stuck.

**Comment by Martin2112** [comment]
Looks like your suggestion for the lambda params fixes the OSX build.

**Comment by Martin2112** [comment]
Newer versions of LLVM produce seem to produce more compilation errors that used to be warnings or are new. I'm testing building openssl with `no-asm` config at the moment.

**Comment by Martin2112** [comment]
That, combined with the de-lambdaing appears to fix it. I'll clean it up and send a PR.

**Comment by Martin2112** [comment]
Proposed fixes in #1450.

**Comment by Martin2112** [comment]
@ahedberg sorry for the problems. If you rebase against master hopefully things will be fixed.

**Comment by daviddrysdale** [comment]
I think closing and re-opening might trigger a new merge and Travis run...

**Comment by daviddrysdale** [comment]
Ah no, my bad, I didn't see the manual-merge needed.

**Pull request merged**
