### PR TITLE
Server cleanup

### PR DESCRIPTION
**Pull request by pphaneuf**
A few somewhat unrelated things, but separate cleanups for ease of review.

### CODE REVIEW

**Comment by pphaneuf** [comment]
I was careful not to change much of significance in `server.h`, shouldn't be too conflicty (and I don't expect you'll be doing too much in `server.cc` itself, other than maybe remove a method?)...

**Comment by Martin2112** [comment]
I see merge conflicts.

**Comment by pphaneuf** [comment]
I'm looking at your changes in 291276eba06fd29c5f2b81e1bd8f13eb0ae2306d, and I see many different, distinct changes that would be worth their own PRs (or, at the very least, commits). :wink:

Like "moving the flags to server.cc", "add Server::ProvideDatabase", "replace CertificateHandler ctor parameters with Server*", etc...

**Comment by Martin2112** [comment]
I refer to the Hon. Gentleman to his PR entitled "A few somewhat unrelated
things".

**Comment by pphaneuf** [comment]
> (or, at the very least, commits)

:wink:

**Comment by Martin2112** [comment]
I haven't created a PR yet. I can still split it up.

**Comment by pphaneuf** [comment]
Indeed, it's a mere question of "git rebase" (what could go wrong?). :laughing:

**Pull request merged**
