### PR TITLE
Fix TypeError: load_pem_public_key() takes exactly 2 arguments (1 given)

### PR DESCRIPTION
**Pull request by unreturned**
Fix
```
./print_log_list.py --log_list=log_list.json --log_list_schema=log_list_schema.json --signature=log_list.sig --signer_key=log_list_pubkey.pem
Traceback (most recent call last):
  File "./print_log_list.py", line 129, in <module>
    app.run(main)
  File "/home/kovalkov/.local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/kovalkov/.local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./print_log_list.py", line 102, in main
    if not is_signature_valid(json_data, FLAGS.signature, FLAGS.signer_key):
  File "./print_log_list.py", line 55, in is_signature_valid
    pubkey = serialization.load_pem_public_key(pubkey_pem)
TypeError: load_pem_public_key() takes exactly 2 arguments (1 given)
```

### CODE REVIEW

**Comment by unreturned** [comment]
I signed it!

**Comment by pphaneuf** [comment]
Could you add yourself to the `AUTHORS` and `CONTRIBUTORS` files, please? Otherwise ready to merge! 😃

**Comment by unreturned** [comment]
> Could you add yourself to the `AUTHORS` and `CONTRIBUTORS` files, please? Otherwise ready to merge!

Donw, please, check it.

**Comment by unreturned** [comment]
I`m very sorry, i correct myself with style of file and email with CLA.
Dear @pphaneuf , gentle ping.
Thank you.

**Comment by pphaneuf** [comment]
Thanks!

**Pull request merged**
