### PR TITLE
Make Database<>::ScanEntries const.

### PR DESCRIPTION
**Pull request by pphaneuf**
Shamelessly stolen from #777, which I couldn't bear to see so complex. :wink:

### CODE REVIEW

**Comment by AlCutter** [comment]
Like a thief in the night, stealing yer pillows.

**Comment by pphaneuf** [comment]
PRESSING GREEN BUTTONS ON MY PR, MAKING ME LOOK MESSY! :wink:

**Comment by AlCutter** [comment]
It's morally mine, and you're on holiday anyway.
Just wait 'til you see what I've done to your desk.

**Comment by pphaneuf** [comment]
I'm only partially on holiday. And now I'm a bit worried about my desk... :smiley:

**Pull request merged**
