### PR TITLE
Disable Keep-Alive header from postAndParse

### PR DESCRIPTION
**Pull request by fhossain**
@jsha here is the pull request to fix requests to Googles CT logs when using postAndParse

### CODE REVIEW

**Comment by fhossain** [comment]
I signed it! 

    On Tuesday, June 7, 2016 11:35 AM, googlebot <notifications@github.com> wrote:
 

 Thanks for your pull request. It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA). 📝 Please visit https://cla.developers.google.com/ to sign.Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.   
   - If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.
   - If you signed the CLA as a corporation, please let us know the company's name.

**Comment by jsha** [comment]
LGTM. A maintainer will have to merge it though; I don't have commit on this repo.

**Comment by pphaneuf** [comment]
I see your email address in the commit is `@salesforce.com`, is this made on behalf of your employer? We might be needing a corporate CLA, for that case?

Either way, you should add yourself to the `CONTRIBUTORS` (see the instructions at the top of that file), and probably `AUTHORS` (either Salesforce or yourself) as well. :smiley:

**Comment by pphaneuf** [comment]
Oh, and I'd recommend that you add your GitHub username to the contact information on https://cla.developers.google.com/clas. The googlebot sometimes struggle if you use different email addresses, the GitHub username helps a lot! :wink:

**Comment by pphaneuf** [comment]
It's LGTM to me, though, as soon as the comments above are addressed, I'll merge.

**Comment by fhossain** [comment]
@pphaneuf I made the change as myself. I was logged into my salesforce account when I did the change. I assume the personal CLA should still be good. When I go to the top of the file, I do see myself as one of the CONTRIBUTORS. Is there something beyond that? Also, added my github username in my CLA contact information.

**Comment by pphaneuf** [comment]
In this file? I don't see your name?

https://github.com/google/certificate-transparency/blob/master/CONTRIBUTORS

**Comment by pphaneuf** [comment]
And for Salesforce, they're your employer, right? The CLA has to be signed by the copyright/IP owner, and with a lot of IT companies, that's the employer, which is why I was checking.

If you personally own the copyright/IP on this contribution (however small it is!), then it's all fine (and you should add yourself to the `AUTHORS` file as well!).

**Comment by fhossain** [comment]
@philandstuff  thanks for the tip. Added myself to the CONTRIBUTORS list. This means I will have to submit CCLA instead. Working on that now.

**Comment by fhossain** [comment]
@pphaneuf I opt to go with CLA and not CCLA for this commit. Do you need me to update AUTHORS as well or are we good with CONTRIBUTORS only. If it is the latter we should be good to merge.

**Comment by pphaneuf** [comment]
I guess with the individual CLA, it's on you to make sure you're the copyright/IP owner, so it's on you? In that case, add yourself to the `AUTHORS`, and we're done.

**Comment by pphaneuf** [comment]
GitHub claims that there would be conflicts now? If you could rebase on top of the current `master` on our side, that'd be great, but no worries if you can't, I can deal with it manually...

**Comment by fhossain** [comment]
@pphaneuf the conflict has been removed. You should be good with the merge now.

**Comment by pphaneuf** [comment]
Thanks!

**Pull request merged**
