### PR TITLE
Allow trusted roots to be in a single file.

### PR DESCRIPTION
**Pull request by benlaurie**

### CODE REVIEW

**Comment by benlaurie** [comment]
@googlebot you are a dork.

**Comment by eranmes** [comment]
LGTM assuming Travis is happy.

**Comment by benlaurie** [comment]
Are you assigning these to me in the hope I'll resolve the conflicts and commit?

**Comment by RJPercival** [comment]
It's a gentle nudge to either resolve the conflicts and get the PR merged, or close the PR. [This codebase has been deprecated](https://github.com/google/certificate-transparency/blob/master/README.md#c-log-server-deprecation-notice), so our team will not be adopting any abandoned PRs.

**Pull request closed without merging**
