### PR TITLE
Add experimental XJSON entry server.

### PR DESCRIPTION
**Pull request by AlCutter**

### CODE REVIEW

**Comment by pphaneuf** [comment]
LGTM

**Comment by Martin2112** [comment]
He's modified the serializer code as well. I'm trying to think of a good joke about merge conflicts but failing so far.

**Comment by pphaneuf** [comment]
Other than `Deserializer::ReadMerkleTreeLeaf`, it's mostly adding code, shouldn't be too bad... Smaller PRs are easier to rebase and fix conflicts? :wink:

**Comment by Martin2112** [comment]
Maybe. I think this is going to conflict though where I've changed the same
methods. We'll see.

Martin

**Pull request merged**
