### PR TITLE
Migrate CertChecker::IsTrusted to util::StatusOr<bool>.

### PR DESCRIPTION
**Pull request by pphaneuf**

### CODE REVIEW

**Comment by Martin2112** [comment]
Looks simpler. We're losing the exact reason the chain didn't verify but I don't think we do anything with that anyway.

**Comment by pphaneuf** [comment]
Programmatically, yes, but the error messages are a bit more detailed. Also, I was surprised that there's a bunch of values for the `enum` that simply weren't used? Like `UNSUPPORTED_ALGORITHM_IN_CERT_CHAIN`, for example...

**Comment by Martin2112** [comment]
The comments in the file implied that the different return values were
planned to be used but this never happened. I think it's better to clean
this stuff up because people then don't have to read it and work that out.

**Comment by pphaneuf** [comment]
Agreed, this should have been a case of [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it), having unused values like that is just setting up someone for disappointment.

**Pull request merged**
