### PR TITLE
Remove unused flag for stats collection

### PR DESCRIPTION
**Pull request by Martin2112**
The log_stats_frequency_seconds flag was defined in all 3 servers and I can't see any references to it elsewhere.

### CODE REVIEW

**Comment by pphaneuf** [comment]
LGTM

**Comment by Martin2112** [comment]
That was quick work!

**Comment by pphaneuf** [comment]
It was a small, distinct PR. :smiley:

**Comment by pphaneuf** [comment]
Let it finish on Travis first, of course, that should tell us if there was some obscure reference to it (but I expect it'll be fine).

**Pull request merged**
