### PR TITLE
Don't ignore the result of the Go tests in the Travis build.

### PR DESCRIPTION
**Pull request by pphaneuf**

### CODE REVIEW

**Comment by pphaneuf** [comment]
Did I just reveal a bug?

```
=== RUN   TestAddLeaf
--- FAIL: TestAddLeaf (0.00s)
panic: runtime error: cgo argument has Go pointer to Go pointer [recovered]
	panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 21 [running]:
panic(0x4178040, 0xc820062520)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
testing.tRunner.func1(0xc82009c090)
	/usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:467 +0x192
panic(0x4178040, 0xc820062520)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:426 +0x4e9
github.com/google/certificate-transparency/go/merkletree.(*CPPMerkleTree).CurrentRoot(0xc82007a0e0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/build/google/install/go/src/github.com/google/certificate-transparency/go/merkletree/merkle_tree.go:55 +0x15e
github.com/google/certificate-transparency/go/merkletree.TestAddLeaf(0xc82009c090)
	/Users/travis/build/google/install/go/src/github.com/google/certificate-transparency/go/merkletree/merkle_tree_test.go:79 +0x481
testing.tRunner(0xc82009c090, 0x428c7b8)
	/usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:473 +0x98
created by testing.RunTests
	/usr/local/Cellar/go/1.6/libexec/src/testing/testing.go:582 +0x892
FAIL	github.com/google/certificate-transparency/go/merkletree	0.036s
```

**Comment by taknira** [comment]
Looks like your PR is working as intended if it's now correctly causing go build/test failures to be reported!

**Comment by pphaneuf** [comment]
Yeah, I agree, this PR does work, but maybe we'd want another PR to fix this problem first, to avoid breaking the master branch? @AlCutter, any idea what this is? Just retry the build, see if it's a flake?

**Comment by pphaneuf** [comment]
A bit more info on this, now there's a workaround, but we should really fix issue #1152 and revert that workaround as soon as possible.

**Pull request merged**
